// src/components/Icons.jsx
import {
  Home,
  Building2,
  Recycle,
  FileText,
  Calendar,
  Paperclip,
  Bell,
  User,
  LayoutDashboard,
  ClipboardList,
  BarChart3,
  Settings,
  LogOut,
  Check,
  AlertTriangle,
  Info,
  Upload,
  Download,
  Printer,
  FileSpreadsheet,
  FileDown,
  Plus,
  Pencil,
  Trash2,
  Eye,
  Shield,
  ShieldCheck,
  Key,
  MapPin,
  Users,
  Database,
  Server,
  ChevronRight,
  ChevronDown,
  Menu,
  X,
  Search,
  Filter,
  RefreshCw,
  FileCheck,
  FileClock,
  TrendingUp,
  Award,
  Inbox,
  Archive,
  Activity,
  CheckCircle2,
  XCircle,
  Clock,
  Send,
  RotateCcw,
  Lock,
  Unlock,
  Layers,
} from 'lucide-react';

export const ICONS = {
  home: Home,
  building: Building2,
  recycle: Recycle,
  file: FileText,
  calendar: Calendar,
  paperclip: Paperclip,
  bell: Bell,
  user: User,
  dashboard: LayoutDashboard,
  clipboard: ClipboardList,
  chart: BarChart3,
  settings: Settings,
  logout: LogOut,
  check: Check,
  alert: AlertTriangle,
  info: Info,
  upload: Upload,
  download: Download,
  printer: Printer,
  excel: FileSpreadsheet,
  fileDown: FileDown,
  plus: Plus,
  pencil: Pencil,
  trash: Trash2,
  eye: Eye,
  shield: Shield,
  shieldCheck: ShieldCheck,
  key: Key,
  pin: MapPin,
  users: Users,
  database: Database,
  server: Server,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  menu: Menu,
  close: X,
  search: Search,
  filter: Filter,
  refresh: RefreshCw,
  fileCheck: FileCheck,
  fileClock: FileClock,
  trending: TrendingUp,
  award: Award,
  inbox: Inbox,
  archive: Archive,
  activity: Activity,
  checkCircle: CheckCircle2,
  xCircle: XCircle,
  clock: Clock,
  send: Send,
  return: RotateCcw,
  lock: Lock,
  unlock: Unlock,
  layers: Layers,
};

export default function Icon({ name, size = 20, strokeWidth = 2, ...rest }) {
  const Comp = ICONS[name] || Info;
  return <Comp size={size} strokeWidth={strokeWidth} {...rest} />;
}